import type { Metadata } from "next";
import Link from "next/link";
import LegalPage, { GITHUB_URL } from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms for using Mail-man.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="October 2, 2026">
      <section>
        <p>
          These terms apply when you use Mail-man. By signing in, you agree to them. If you don&apos;t agree, please
          don&apos;t use the service.
        </p>
      </section>

      <section>
        <h2>The service</h2>
        <p>
          Mail-man is a free email client for Gmail with AI features. It is a personal project, offered as is.
          Features may change, and the service may be paused or shut down at any time.
        </p>
      </section>

      <section>
        <h2>Your account and keys</h2>
        <ul>
          <li>You sign in with your own Google account and are responsible for what is sent from it.</li>
          <li>
            AI features use the API key you provide. Usage is billed to you by that provider, under its terms. Keep
            an eye on your provider&apos;s usage limits.
          </li>
          <li>You must follow Google&apos;s terms and the terms of your AI provider when using Mail-man.</li>
        </ul>
      </section>

      <section>
        <h2>Acceptable use</h2>
        <p>
          Don&apos;t use Mail-man to send spam, to harass anyone, to break the law, or to try to access other
          people&apos;s data or disrupt the service.
        </p>
      </section>

      <section>
        <h2>AI output</h2>
        <p>
          Summaries, categories, suggested replies and extracted to-dos are generated by AI and can be wrong. Check
          them before relying on them, and read anything before you send it.
        </p>
      </section>

      <section>
        <h2>Your data</h2>
        <p>
          How Mail-man handles your data is described in the <Link href="/privacy">Privacy Policy</Link>. You can
          delete your data at any time from Settings.
        </p>
      </section>

      <section>
        <h2>No warranty</h2>
        <p>
          Mail-man is provided &quot;as is&quot;, without warranties of any kind. To the extent the law allows, the
          people behind Mail-man are not liable for any loss arising from its use, including lost or misdirected
          email or AI provider charges.
        </p>
      </section>

      <section>
        <h2>Contact</h2>
        <p>
          Questions can be filed as an issue on <a href={GITHUB_URL} target="_blank" rel="noopener noreferrer">GitHub</a>.
        </p>
      </section>
    </LegalPage>
  );
}
